### ISSUE TITLE
Issues with anchors and UNKNOWN_BASE_TYPE

### ISSUE THREAD

**Issue by kasandell** [lithic-com/lithic-openapi#1]
Hi All, 

I'm currently trying to use the spec provided to generate a client in Rust (but experiencing these issues regardless of output language). As is, with the spec, when I run either `openapi-generator` or `openapi-generator-cli`, both on versions `7.1.0`, any section that uses YAML anchors causes the following issues:
```
openapi-generator-cli generate -g rust \
-i https://raw.githubusercontent.com/lithic-com/lithic-openapi/main/lithic-openapi.yml \
-o lithic_client
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 9, Warning count: 17
Errors:
	-attribute .components.schemas.EventSubscription.enum is not of type `array` (#/components/schemas/EventSubscription)
	-attribute .components.schemas.Event.enum is not of type `array` (#/components/schemas/Event)
	-attribute .components.schemas.BankAccountApiResponse.enum is not of type `array` (#/components/schemas/BankAccountApiResponse)
	-attribute .components.schemas.MessageAttempt.enum is not of type `array` (#/components/schemas/MessageAttempt)
	-attribute .components.schemas.FinancialAccount.enum is not of type `array` (#/components/schemas/FinancialAccount)
	-attribute .components.schemas.Balance.enum is not of type `array` (#/components/schemas/Balance)
	-attribute .components.schemas.AggregateBalance.enum is not of type `array` (#/components/schemas/AggregateBalance)
	-attribute .components.schemas.Dispute.enum is not of type `array` (#/components/schemas/Dispute)
	-attribute .components.schemas.Transaction.enum is not of type `array` (#/components/schemas/Transaction)
Warnings:
	-attribute .components.schemas.EventSubscription.enum is not of type `array` (#/components/schemas/EventSubscription)
	-attribute .components.schemas.Event.enum is not of type `array` (#/components/schemas/Event)
	-attribute .components.schemas.BankAccountApiResponse.enum is not of type `array` (#/components/schemas/BankAccountApiResponse)
	-attribute .components.schemas.MessageAttempt.enum is not of type `array` (#/components/schemas/MessageAttempt)
	-attribute .components.schemas.FinancialAccount.enum is not of type `array` (#/components/schemas/FinancialAccount)
	-attribute .components.schemas.Balance.enum is not of type `array` (#/components/schemas/Balance)
	-attribute .components.schemas.AggregateBalance.enum is not of type `array` (#/components/schemas/AggregateBalance)
	-attribute .components.schemas.Dispute.enum is not of type `array` (#/components/schemas/Dispute)
	-attribute .components.schemas.Transaction.enum is not of type `array` (#/components/schemas/Transaction)

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:684)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:711)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:511)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

I've gotten around this by using YQ to expand these sections verbosely, but am now faced with the following.
```
WARN  o.o.codegen.DefaultCodegen - codegenModel is null. Default to UNKNOWN_BASE_TYPE
```
which generates the `UNKNOWN_BASE_TYPE` symbol in the client and causes compilation issues. 

I was wondering what version of the openapi generator is being used to create a client from this file? Additionally, if there is any information on the underlying jackson version being used to parse the YAML, since that seems to be the root cause of not being able to parse anchors properly.

**Comment by rattrayalex** [comment]
👋 hi there @kasandell ! I help Lithic produce their SDKs using the [Stainless](https://stainlessapi.com) code generator. We don't yet produce a Rust client, but we hope to do this in the future.

In the meantime, I'd generally recommend avoiding the openapi-generator; it has a hard time with a lot of things, and tends to take a fair bit of tweaking for things to sorta work.

Instead, you might try alternative Rust client generators. I've heard good things about some of them but sadly I can't remember which one I've heard the best things about:

1. https://crates.io/crates/paperclip
2. https://crates.io/crates/progenitor

If YAML anchors continue to be a nuisance, you might consider converting the spec [to JSON](https://gist.github.com/Ciantic/3788b61297c3dd8ea79233f161ecf84f) first (though I imagine a codegen tool implemented in Rust will be less likely to have these sorts of problems).

I hope this helps? And I'm quite curious if either or both of these generators work well for your needs!
